name: Server
on: 
  workflow_dispatch:
jobs:
  RunServer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Create report file
        run: |
          pip install https://github.com/python-telegram-bot/python-telegram-bot/archive/2642ecc7379907a72dc5ef68791b30b18c18c1d2.zip requests
          python server.py
