name: GitHub Actions Demo
on: 
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Create report file
        run: python server.py
